######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
Load(Filename='/home/scu/checkout/mantidproject/mantid/Test/AutoTestData/BSS_11841_event.nxs',OutputWorkspace='BSS_11841_event')
CalibrateToElasticLine(InputWorkspace='BSS_11841_event',OutputWorkspace='BSS_11841_event',ElasticPositionsFilename='/home/scu/checkout/sic/playarea/guessElasticLine.dat')
